package models

type MtgSet struct {
	SetId          string
	SetCode        string
	SetName        string
	SetType        string
	SetUri         string
	SetSearchUri   string
	ScryfallSetUri string
}

type Related struct {
	Object    string
	Id        string
	Component string
	Name      string
	TypeLine  string
	Uri       string
}

type Cards struct {
	OracleId         string
	Object           string
	CardName         string
	Layout           string
	ManaCost         string
	Cmc              float64
	TypeLine         string
	Power            string
	Toughness        string
	Colors           []string
	ColorIdentity    []string
	Keywords         []string
	ProducedMana     []string
	Reserved         bool
	StandardF        bool
	FutureF          bool
	HistoricF        bool
	TimelessF        bool
	GladiatorF       bool
	PioneerF         bool
	ExplorerF        bool
	ModernF          bool
	LegacyF          bool
	PauperF          bool
	VintageF         bool
	PennyF           bool
	CommanderF       bool
	OathbreakerF     bool
	StandardbrawlF   bool
	BrawlF           bool
	AlchemyF         bool
	PaupercommanderF bool
	DuelF            bool
	PremodernF       bool
	PredhF           bool
	ColorIndicator   []string
	Defense          string
	Loyalty          string
	EdhrecRank       int
	HandModifier     string
	LifeModifier     string
	PennyRank        int
}

type CardFaces struct {
	Artist          string
	ArtistId        string
	Cmc             float64
	ColorIndicator  []string
	Colors          []string
	Defense         string
	FlavorText      string
	IllustrationId  string
	PngUri          string
	BoarderCropUri  string
	ArtCropUri      string
	LargeUri        string
	NormalUri       string
	SmallUri        string
	Layout          string
	Loyalty         string
	ManaCost        string
	Name            string
	Object          string
	OracleId        string
	OracleText      string
	Power           string
	PrintedName     string
	PrintedText     string
	PrintedTypeLine string
	Toughness       string
	TypeLine        string
	Watermark       string
}

type Prints struct {
	CardName          string
	SetId             string
	Lang              string
	OracleId          string
	MtgoId            int
	MtgoFoilId        int
	ArenaId           int
	TcgplayerId       int
	TcgplayerEtchedId int
	ReleasedAt        string
	Games             []string
	AttractionLights  []int
	Oversized         bool
	OracleText        string
	CollectorNumber   string
	Digital           bool
	Rarity            string
	OldschoolF        bool
	CardBackId        string
	Artist            string
	IllustrationId    string
	BorderColor       string
	Frame             string
	FullArt           bool
	Textless          bool
	Booster           bool
	StorySpotlight    bool
	TcgArticlesUri    string
	TcgDecksUri       string
	EdhrecUri         string
	TcgBuyUri         string
	CardmarketBuyUri  string
	CardhoarderBuyUri string
	PrintsSearchUri   string
	Related           []Related
	FlavorName        string
	FrameEffects      []string
	SecurityStamp     string
	PreviewedAt       string
	PreviewUri        string
	PreviewSource     string
	ContentWarning    bool
	BorderEffects     []string
	MultiverseIds     []int
	GathererUri       string
	ScryfallUri       string
	RulingsUri        string
	HighresImage      bool
	ImageStatus       string
	Foil              bool
	NotFoil           bool
	Finishes          []string
	Promo             bool
	PromoTypes        []string
	Reprint           bool
	Variation         bool
	VariationOf       string
	PriceUsd          string
	PriceUsdFoil      string
	PriceUsdEtched    string
	PriceEur          string
	PriceEurFoil      string
	PriceTix          string
	PrintedName       string
	PrintedText       string
	PrintedTypeLine   string
	FlavorText        string
	CardmarketId      int
	CardFaces         []CardFaces
	Uri               string
	Id                string
	PngUri            string
	BoarderCropUri    string
	ArtCropUri        string
	LargeUri          string
	NormalUri         string
	SmallUri          string
	Watermark         string
	PurchaseUris      []string
}
